# Generated by Django 3.1.4 on 2020-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=300)),
                ('user_email', models.CharField(max_length=300)),
                ('salt', models.CharField(max_length=40)),
                ('is_active', models.IntegerField(max_length=2)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
    ]
