# Generated by Django 3.1.4 on 2020-12-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
